# Generated by Django 3.1.6 on 2021-02-13 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bausparvertrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bausparsumme', models.IntegerField()),
                ('abschlussgebuehren_prozent', models.IntegerField(null=True)),
                ('abschlussgebuehren_in_euro', models.IntegerField(null=True)),
                ('laufende_gebuehren_prozent', models.IntegerField(null=True)),
                ('laufende_gebuehren_in_euro', models.IntegerField(null=True)),
                ('laufende_gebuehren_zeitraum', models.CharField(choices=[('JAEHRLICH', 'jährlich'), ('HALBJAEHRLICH', 'halbjährlich'), ('VIERTELJAEHRLICH', 'vierteljährlich'), ('MONATLICH', 'monatlich'), ('EINMALIG', 'einmalig')], max_length=16)),
                ('zinsen_ansparphase', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bausparvertraege', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sparbeitrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.IntegerField()),
                ('erste_buchung', models.DateField()),
                ('letzte_buchung', models.DateField(null=True)),
                ('bausparvertrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparbeitraege', to='bauspartrackerapp.bausparvertrag')),
            ],
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('betrag', models.IntegerField()),
                ('art', models.CharField(choices=[('ABSCHLUSSGEBUEHR', 'Abschlussgebühr'), ('LAUFENDE_GEBUEHR', 'Laufende Gebühr'), ('SPARBEITRAG', 'Sparbeitrag')], max_length=16)),
                ('bausparvertrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='bauspartrackerapp.bausparvertrag')),
                ('sparbetrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='bauspartrackerapp.sparbeitrag')),
            ],
        ),
    ]
